#!/bin/sh

[ -f /etc/sysconfig/config ] && . /etc/sysconfig/config
DAEMON=${MINISATIP:-/sbin/minisatip-legacy}
PIDFILE=/var/run/minisatip.pid
LOCAL_IP=$(ip route get 1 | awk '{print $7; exit}')
MINISATIP_ARGS="-g -z /etc/sysconfig/minisatip -p http://$LOCAL_IP/playlist.m3u"

if test -r /etc/sysconfig/oscam/oscam.server; then
  MINISATIP_ARGS="$MINISATIP_ARGS --dvbapi 127.0.0.1:9000"
fi

case "$1" in
  start)
    printf "starting minisatip: "
    start-stop-daemon -S -x "$DAEMON" -- $MINISATIP_ARGS
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "stopping minisatip: "
    start-stop-daemon -K -x "$DAEMON"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
