#!/bin/sh

if ! test -r /etc/dropbear/dropbear_ed25519_host_key; then
  mkdir -p /etc/dropbear
  if test -r /etc/sysconfig/dropbear_ed25519_host_key; then
    cp /etc/sysconfig/dropbear_ed25519_host_key /etc/dropbear
  else
    dropbearkey -t ed25519 -f /etc/dropbear/dropbear_ed25519_host_key
    cp /etc/dropbear/dropbear_ed25519_host_key /etc/sysconfig
  fi
fi

export HOME=/root
if test -r /etc/sysconfig/authorized_keys ; then
  mkdir -p $HOME/.ssh
  cp /etc/sysconfig/authorized_keys $HOME/.ssh/authorized_keys
  chmod 0600 $HOME/.ssh/authorized_keys
fi

