#!/bin/sh

DAEMON=/usr/sbin/httpd
PIDFILE=/var/run/httpd.pid
HTTPD_ARGS="-h /mnt/data"

case "$1" in
  start)
    printf "starting httpd: "
    start-stop-daemon -S -p "$PIDFILE" -x "$DAEMON" -- $HTTPD_ARGS
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "stopping httpd: "
    start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit $?
